import streamlit as st
st.button("Click me!")
st.checkbox("Check me!")
st.radio("Choose one:", ["Option 1", "Option 2", "Option 3"])
st.selectbox("Select one:", ["Choice A", "Choice B", "Choice C"])
st.multiselect("Select multiple:", ["Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6"])
st.slider("Slide me:", 0, 100, 50)
st.text_input("Enter text:")
st.text_area("Enter more text:")
st.number_input("Enter a number:", min_value=0, max_value=100, value=50)
st.date_input("Pick a date:")
st.time_input("Pick a time:")
st.file_uploader("Upload a file:")
st.color_picker("Pick a color:")
st.caption("This is a caption.")
st.markdown("This is **markdown** text.")
st.latex(r"E=mc^2")
st.metric("Temperature", "72 °F", "+1.2 °F")
st.progress(0.5)
st.spinner("Loading...")
st.balloons()
st.toast("This is a toast notification!", icon="🎉")
st.error("This is an error message.")
st.warning("This is a warning message.")
st.info("This is an info message.")
st.success("This is a success message.")
st.exception(Exception("This is an exception message."))
st.json({"key": "value", "number": 42})
st.dataframe({"Column 1": [1, 2, 3], "Column 2": ["A", "B", "C"]})
st.table([["Row 1", 1], ["Row 2", 2], ["Row 3", 3]])
st.line_chart([1, 2, 3, 4, 5])
 # Network URL: http://192.168.32.221:8501